### ISSUE TITLE
Java Keytool Conflict

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/keytool-cli#11]
I just compiled keytool on relatively new macOS Big Sur 11.1 system:

```
Ran 26 tests.

OK
*** Keytool built.
Next step: sudo make install
# sudo make install
Password:
source set_build_paths.sh && cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make install
install -d /usr/local/bin
install keytool /usr/local/bin
# keytool
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
# which keytool
/usr/bin/keytool
# /usr/local/bin/keytool
keytool: No outputs requested.
Try `keytool --help' or `keytool --usage' for more information.
#
```

This didn't happen on my earlier Catalina development machine. This is a relatively fresh install, so unclear what might have installed the java keytool.

We may have to consider renaming not only keytool but also seedtool.

**Comment by wolfmcnally** [comment]
If you have Java keytool installed, you will need to make sure your .bashprofile or .zprofile file adds /usr/local/bin to your $PATH environment variable first.

**Comment by ChristopherA** [comment]
This should only be closed when it is documented clearly with install notes.
